# Generated by Django 2.1.4 on 2019-01-09 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0002_auto_20190102_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api_key',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
